# launcher name & url
launcher_name=VLzyLauncher
launcher_app_name=VLzy Launcher
launcher_short_name=VLzy
url_home=https://github.com/Nadzil123/VLzyLauncher

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
#curseforge_api_key=xxx

# launcher version
launcher_version_code=200048
launcher_version_name=1.0.0-alpha.1-20261003
